Console.WriteLine();
Console.Write("From = ");
var x = Convert.ToInt32(Console.ReadLine());
Console.Write("To = ");
var y = Convert.ToInt32(Console.ReadLine());
Console.WriteLine();
Console.WriteLine($"{x}x1={x*1}");
Console.WriteLine($"{x}x2={x*2}");
Console.WriteLine($"{x}x3={x*3}");
Console.WriteLine($"{x}x4={x*4}");
Console.WriteLine($"{x}x5={x*5}");
Console.WriteLine($"{x}x6={x*6}");
Console.WriteLine($"{x}x7={x*7}");
Console.WriteLine($"{x}x8={x*8}");
Console.WriteLine($"{x}x9={x*9}");
Console.WriteLine($"{x}x10={x*10}");
Console.WriteLine();
Console.WriteLine($"{y}x1={y*1}");
Console.WriteLine($"{y}x2={y*2}");
Console.WriteLine($"{y}x3={y*3}");
Console.WriteLine($"{y}x4={y*4}");
Console.WriteLine($"{y}x5={y*5}");
Console.WriteLine($"{y}x6={y*6}");
Console.WriteLine($"{y}x7={y*7}");
Console.WriteLine($"{y}x8={y*8}");
Console.WriteLine($"{y}x9={y*9}");
Console.WriteLine($"{y}x10={y*10}");
Console.WriteLine();

